import { Injectable, OnModuleInit } from '@nestjs/common';
import OpenAI from 'openai';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { RepomixService } from './repomix.service';
import { AIActivityLoggerService } from './ai-activity-logger.service';
import { Task } from 'src/interfaces';
import { ENV } from 'src/env';
import path from 'path';


@Injectable()
export class AIAgentService implements OnModuleInit {
  private openai: OpenAI;
  private mcpClient: Client;
  private availableTools: any[];

  constructor(private repomix: RepomixService) {}

  async onModuleInit() {
    this.openai = new OpenAI({ baseURL: ENV.LLM_API_URL, apiKey: ENV.LLM_API_KEY });
    this.mcpClient = new Client({ name: ENV.APPNAME, version: ENV.VERSION }, { capabilities: {}});

    const transport = new StdioClientTransport({
      command: 'npx',
      args: [
        '-y',
        '@modelcontextprotocol/server-filesystem',
        path.join(ENV.FOLDER_STORAGE, 'repo')
      ]
    });

    await this.mcpClient.connect(transport);
    
    const { tools } = await this.mcpClient.listTools();
    this.availableTools = tools.map(t => ({
      type: 'function',
      function: {
        name: t.name,
        description: t.description,
        parameters: t.inputSchema
      }
    }));

    console.log(`🔧 Loaded ${this.availableTools.length} MCP tools`);
  }

  async executeTask(
    task: Task, 
    taskIndex: number, 
    logger: AIActivityLoggerService,
    repoPath: string
  ): Promise<void> {
    // Genera il prompt con contesto del progetto se disponibile
    const systemPrompt = await this.buildSystemPrompt(task);

    let messages: any[] = [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: `Please complete this task: ${task.description}` }
    ];

    const maxIterations = 10;
    let iteration = 0;

    while (iteration < maxIterations) {
      iteration++;
      logger.incrementLLMCalls(taskIndex);

      const response = await this.openai.chat.completions.create({
        model: ENV.LLM_MODEL,
        messages,
        tools: this.availableTools,
        tool_choice: 'auto',
        temperature: 0.1
      });

      const message = response.choices[0].message;
      messages.push(message);

      if (!message.tool_calls || message.tool_calls.length === 0) {
        if (message.content) {
          logger.log('info', `AI response: ${message.content}`);
        }
        break;
      }

      for (const toolCall of message.tool_calls) {
        const toolStartTime = new Date();
        
        try {
          const result = await this.mcpClient.callTool({
            name: toolCall.function.name,
            arguments: JSON.parse(toolCall.function.arguments)
          });

          await logger.logToolCall(
            taskIndex,
            toolCall.function.name,
            JSON.parse(toolCall.function.arguments),
            toolStartTime,
            true
          );

          messages.push({
            role: 'tool',
            tool_call_id: toolCall.id,
            content: JSON.stringify(result.content)
          });
        } catch (error) {
          await logger.logToolCall(
            taskIndex,
            toolCall.function.name,
            JSON.parse(toolCall.function.arguments),
            toolStartTime,
            false
          );
          throw error;
        }
      }
    }

    if (iteration >= maxIterations) {
      throw new Error('Max iterations reached');
    }
  }

  private async buildSystemPrompt(task: Task): Promise<string> {
    let prompt = `You are an expert code assistant working on a Node.js mono-repository project. You have access to filesystem tools to read, write, and modify files.

Your current task is to implement the requested changes in the codebase with precision and following best practices.`;

    // Aggiungi il contesto del progetto se Repomix è disponibile
    const projectContext = await this.repomix.getSmartProjectContext(task);
    
    if (projectContext) {
      prompt += `

## Project Context

The following is a comprehensive overview of the project structure and codebase generated by Repomix. Use this context to understand the architecture, patterns, and conventions used in the project.

${projectContext}

---
`;
    }

    // Aggiungi il contesto del task
    prompt += `

## Task Context

**Description:** ${task.description}

**Related files:** ${task.files.join(', ')}
`;

    if (task.context) {
      prompt += `
**Additional context:**
\`\`\`
${task.context}
\`\`\`
`;
    }

    prompt += `

## Guidelines

- Make precise, focused changes that align with the project's existing patterns and architecture
- Follow the code style and conventions evident in the project context
- Add comments where helpful, following the project's commenting style
- Use TypeScript/JavaScript best practices for Node.js development
- Consider the mono-repo structure when making changes
- Ensure imports and dependencies are correctly resolved
- Test your changes mentally before writing them
- Use the filesystem tools to read existing code before making modifications
- When creating new files, place them in the appropriate package/directory based on the project structure

Begin by understanding the relevant parts of the codebase, then implement the required changes step by step.`;

    return prompt;
  }
}