FROM node:20-alpine

# Installa git
RUN apk add --no-cache git openssh-client

WORKDIR /app

# Copia package files
COPY ./package*.json ./
RUN npm install

# Copia il codice sorgente
COPY . ./

# Build
RUN npm run build



# Healthcheck
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 CMD node -e "console.log('healthy')" || exit 1

CMD ["node", "dist/main.js"]